MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH: '/home/inversionproject/.cache/torch/hub/checkpoints/resnet50-19c8e357.pth'
  METRIC_LOSS_TYPE: 'triplet_center'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'yes'
  N_EMBD: 256
  N_HEAD: 2
  N_LAYER: 4
  EMBD_PDROP: 0.1
  ATTN_PDROP: 0.1
  RESID_PDROP: 0.1
  AFN: 'gelu'
  CLF_PDROP: 0.1
  TOPK: 20
  LANDMARK: 5



INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10

DATASETS:
  NAMES: ('veri')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 120
  NFORMER_MAX_EPOCHS: 20
  BASE_LR: 0.00035

  CLUSTER_MARGIN: 0.3

  CENTER_LR: 0.5
  CENTER_LOSS_WEIGHT: 0.0005

  RANGE_K: 2
  RANGE_MARGIN: 0.3
  RANGE_ALPHA: 0
  RANGE_BETA: 1
  RANGE_LOSS_WEIGHT: 1

  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  STEPS: [40, 70]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 40
  LOG_PERIOD: 20
  EVAL_PERIOD: 40

TEST:
  IMS_PER_BATCH: 128
  RE_RANKING: 'no'
  WEIGHT: "/home/inversionproject/person-reid/NFormer_vehicle_dataset/outputs/nformer_model.pth"
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'
  TEST_NFORMER: 'NO'

OUTPUT_DIR: "/home/inversionproject/person-reid/NFormer_vehicle_dataset/outputs/softmax_triplet_with_center"


